name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CACHE_NAME: ${{ github.repository_owner }}
      ATTIC_VERSION: b1fb790
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        # attic lives here :)
        name: ${{ env.CACHE_NAME }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build & cache
      run: |
        nix run github:zhaofengli/attic/$ATTIC_VERSION -- login default ${{ secrets.ATTIC_URL }} ${{ secrets.ATTIC_AUTH_TOKEN }}
        nix run github:zhaofengli/attic/$ATTIC_VERSION -- use $CACHE_NAME
        nix build
        nix run github:zhaofengli/attic/$ATTIC_VERSION -- push $CACHE_NAME ./result
