name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ATTIC_URL: https://attic.alexghr.me
      ATTIC_AUTH_TOKEN: ${{ secrets.ATTIC_AUTH_TOKEN }}
      ATTIC_CACHE: public
      ATTIC_CACHE_PUBLIC_KEY: 5MqPjBBGMCWbo8L8voeQl7HXc5oX+MXZ6BSURfMosIo=
      # pin attic and nixpkgs
      ATTIC_FLAKE: github:zhaofengli/attic/b1fb790
      NIXPKGS_FLAKE: github:NixOS/nixpkgs/0eeebd6
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        extra_nix_config: |
          extra-substituters = ${{ env.ATTIC_URL }}/${{ env.ATTIC_CACHE }}
          extra-trusted-public-keys = ${{ env.ATTIC_CACHE }}:${{ env.ATTIC_CACHE_PUBLIC_KEY }}

    - name: Build & cache
      run: |
        nix shell $NIXPKGS_FLAKE#bash $ATTIC_FLAKE --command bash <<EOF
        attic login default ${ATTIC_URL} ${ATTIC_AUTH_TOKEN}
        attic use ${ATTIC_CACHE}

        nix build

        attic push $ATTIC_CACHE ./result
        EOF
