name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CACHE_NAME: ${{ github.repository_owner }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build & cache
      run: |
        nix run github:zhaofengli/attic -- login default ${{ secrets.ATTIC_URL }} ${{ secrets.ATTIC_AUTH_TOKEN }}
        nix build
        nix run github:zhaofengli/attic -- push default ./result
